### PR TITLE
Use buildPlugin() so this can be used on ci.j.io

### PR DESCRIPTION
**Pull request by rtyler**
https://github.com/jenkins-infra/pipeline-library#buildplugin

### CODE REVIEW

**Comment by ccaum** [comment]
@rtyler I'm not sure why the build is failing to compile. It Works On My Machine™. I'm guessing it's a difference in Maven versions, but I don't have a lot of experience building Java projects so I'm not sure how to move forward.

**Comment by rtyler** [comment]
@ccaum I was able to reproduce the error from ci.jenkins.io on my local machine with:

```
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```


I would gamble that your local Java version is still set to Java 7

**Comment by ccaum** [comment]
@rtyler Ah yes. That was it. I'll try to fix this week.

**Comment by rtyler** [comment]
@ccaum I don't know how to do it in Maven, but I would make sure that the bytecode being generated is still Java 7 compatible, otherwise you'll want to update the `jenkins.version` to 2.60.1 if you want to go full Java 8 :smiling_imp:

**Pull request merged**
